Enhance russian translation
solvespace/solvespace pull request #1290
Opened 2022-09-04 12:15 UTC by nick87720z

Lathe and Revolve words were maped to Rotate during translation.
However, russian has words to not lose meaning.

2022-09-04 21:07 UTC, ruevs commented
Токарный станок = lathe - и поетому - "Вы&точить". Понятно.
But I'd like to hear what @Evil-Spirit thinks. I have no clue what the proper terminology is in Russian in the context of mechanical engineering.

2022-09-04 21:17 UTC, ruevs commented
Relates to #1288

2022-09-04 21:52 UTC, nick87720z commented
Yeah, me too.
Somewhat hard case as I don't remember CADs, using such difference
(only tried autocad, kompas and freecad). "Тело точения" or "Тело
поворота" - sound rather unusual despite valid.

2022-10-04 14:42 UTC, ruevs commented
@Evil-Spirit do you have an opinion on this?

2022-10-07 08:02 UTC, Evil-Spirit commented
"Тело вращения" [solid of revolution](https://www.multitran.com/m.exe?s=solid+of+revolution&l1=1&l2=2) is more common for both lathe operators and students. This is geometrical definition. "Выточить" - this will cause brain damage to every who are not lathe operator. So, need to revert all this since I don't like this at all (pointless to remame to less understandable in order to support initial "lathe" instead of "revolve" )
https://github.com/solvespace/solvespace/pull/1290/commits/7bf427e1f6cece5bb937c2eaece9155fb9bd71cd

2022-10-07 08:20 UTC, Evil-Spirit commented
Hey, I just realized that now there is 3 different operations like:

*   revolve by 360
*   revolve by less than 360
*   revolve by more than 360 and shifing by axis

This all should be just single operation! I believe it is possible to merge them into single group without breaking backward compatibility. but if you want to make translation:

Lathe = Тело вращения

Angular lathe / Lathe by angle = Угловое тело вращения  / Тело вращения на угол

2022-10-07 08:23 UTC, Evil-Spirit requested changes

2022-10-07 08:23 UTC, Evil-Spirit commented on res/locales/ru_RU.po
> -msgstr "Тело В&ращения"
leave this or make it "Тело вращения на 360"

2022-10-07 08:23 UTC, Evil-Spirit commented on res/locales/ru_RU.po
> -msgstr "Тело В&ращения"
Тело вращения на угол / Угловое тело вращения

2022-11-05 17:55 UTC, ruevs commented
@nick87720z @Evil-Spirit merged here 31ac8083ae27733b18a6c2f6454104b9efd9fc29 with the discussed changes. I'm pretty sure I did not screw up anything but please take a look.

2022-11-21 09:03 UTC, nick87720z commented
@Evil-Spirit Just for interest - how about "Lathe" -> "Токарный станок", that was my original idea. Also most verbatim translation, carrying original author idea totally preserved.

2022-11-21 11:36 UTC, ruevs commented
> how about "Lathe" -> "Токарный станок",

But in the English version " lathe" is used as a verb - the literal translation is indeed [выточить]()

2022-11-21 11:36 UTC, closed without merging