Update Russian translation
solvespace/solvespace pull request #1355
Opened 2023-04-03 00:54 UTC by prokoudine

Mostly removing the unnecessary title case — that's not how Russian typography works :)

2023-04-03 09:35 UTC, ruevs requested changes
Hello Alexandre,

Thank you for updating the translation. It's nice to see that you are still following SolveSpace considering that the [first article about the open source release in 2013](https://web.archive.org/web/20200219182544/http://libregraphicsworld.org/blog/entry/solvespace-released-under-gpl) is yours :-)

I've added some comments inline. Please take a look.

2023-04-03 09:35 UTC, ruevs commented on res/locales/ru_RU.po
> +"'Ограничители -> Точка на примитиве' перед тем, как применять ограничители "
Are you sure about this?

The term "constraint" in the context that is used in SolveSpace is "ограничение". On the other hand "ограничитель" is "limiter" and does not fit well in my opinion. But Russian is not my native language.

Is there a precedent in some other CAD software that has Russian UI?

This applies to all the other places where you used "ограничители" - I'll not mark them all.

2023-04-03 09:35 UTC, ruevs commented on res/locales/ru_RU.po
> +msgstr "Экспортировать 2D-се&чение…"
2d

2023-04-03 09:35 UTC, ruevs commented on res/locales/ru_RU.po
> +msgstr ""
Why did you remove:
`msgstr "Последние &детали"`
here?

2023-04-03 09:35 UTC, ruevs commented on res/locales/ru_RU.po
> +msgstr "Режим &3D"
3d

2023-04-03 09:35 UTC, ruevs commented on res/locales/ru_RU.po
> +msgstr ""
Do not remove. Use:
`msgstr "Переключить режим размера для спра&вок"`

2023-04-03 09:35 UTC, ruevs commented on res/locales/ru_RU.po
> +msgstr "ребро нулевой длины!"
`msgstr "отрезок нулевой длины!"`
to be consistent with the rest of the UI.

2023-04-03 09:35 UTC, ruevs commented on res/locales/ru_RU.po
> +msgstr "Выделить последовательность граней"
The original is better here, in my opinion. If I'm not mistaken "грань" means "face"/"facet" and is not what is intended.

2023-04-03 09:35 UTC, ruevs commented on res/locales/ru_RU.po
> +msgstr ""
Restore translation.

2023-04-03 09:35 UTC, ruevs commented on res/locales/ru_RU.po
> +msgstr "Новая группа в 3D"
3d

2023-04-04 16:46 UTC, prokoudine commented on res/locales/ru_RU.po
> +"'Ограничители -> Точка на примитиве' перед тем, как применять ограничители "
Fair point. Let's revert that.

2023-04-04 16:47 UTC, prokoudine commented on res/locales/ru_RU.po
> +msgstr "Сохранить &Как…"
Yes, it's a rather common recommendation in i18n teams

2023-04-04 16:47 UTC, prokoudine commented on res/locales/ru_RU.po
> +msgstr "Экспортировать &2D-вид…"
Oh well, okay :)

2023-04-04 16:48 UTC, prokoudine commented on res/locales/ru_RU.po
> +msgstr "&Справка"
Yep

2023-04-04 16:50 UTC, prokoudine commented on res/locales/ru_RU.po
> +"SolveSpace — свободное программное обеспечение: поощряется изменение, "
That's Russian typography rules

2023-04-04 17:08 UTC, prokoudine commented on res/locales/ru_RU.po
> +msgstr "Выделить последовательность граней"
My bad, it's "Выделить последовательность ребер", of course. Unless SolveSpace absolutely needs edges to be "отрезки", in which case it's "Выделить последовательность отрезков". But I looked up the German translation, and it says "Kantenverlauf", so it definitely refers to edges.

2023-04-04 20:33 UTC, ruevs requested changes
Thanks for the update! I "resolved" all the topics you fixed.

Только четыре "ограничител[ь/и]" остались ;-)

2023-04-04 20:33 UTC, ruevs commented on res/locales/ru_RU.po
> +msgstr "&Ограничитель"
"&Ограничения"

2023-04-04 20:33 UTC, ruevs commented on res/locales/ru_RU.po
> +msgstr "Удалить ограничитель совпадения точек"
"oграничение"

2023-04-04 20:40 UTC, ruevs commented on res/locales/ru_RU.po
> +msgstr "Выделить последовательность граней"
Now it is good.

2023-04-04 20:41 UTC, prokoudine commented
If I squash commits, will it play well with the PR?

2023-04-04 20:49 UTC, prokoudine commented
> Or I can do it when merging.

Ah, please do :)

2023-04-04 20:56 UTC, ruevs approved these changes

2023-04-04 21:02 UTC, merged

2023-04-04 21:03 UTC, ruevs commented
Merged. Thanks @prokoudine.