Fix selection bugs
solvespace/solvespace pull request #860
Opened 2020-12-16 16:43 UTC by vespakoen

I noticed that sometimes normals would get selected even when I didn't select them.
So I added some code to visualise the bounding boxes, which showed me this:

<img width="3200" alt="Screenshot 2020-12-16 at 17 21 16" src="https://user-images.githubusercontent.com/876117/102377706-41348400-3fc5-11eb-9163-504fc749e143.png">

Notice the little yellow dots around the center of the drawing, these are the normals of the arcs.

I then also noticed that when in "3d view", the selection didn't work sometimes, this was caused by the selection marquee only having a "depth" of 1 ... "unit" ?

This PR fixes both of these things, I wonder though, if for the BBox we should add a "FlatOverlap / Overlap2d" check that ignores the Z value, right now I am using the VERY_NEGATIVE and VERY_POSITIVE values for the Z range which is not optimal.

Here is the code for drawing the BBoxes by the way if anyone is interested:

```
+        // Draw the bboxes
+        Entity *e;
+        for(e = SK.entity.First(); e; e = SK.entity.NextAfter(e)) {
+            if(e->group != SS.GW.activeGroup) continue;
+            if(e->IsFace() || e->IsDistance()) continue;
+            if(!e->IsVisible()) continue;
+            bool entityHasBBox;
+            BBox entityBBox = e->GetOrGenerateScreenBBox(&entityHasBBox);
+            if (entityHasBBox) {
+                uiCanvas.DrawRect((int)(entityBBox.minp.x - 1) + (int)camera.width / 2,
+                    (int)(entityBBox.maxp.x + 1) + (int)camera.width / 2,
+                    (int)(entityBBox.minp.y - 1) + (int)camera.height / 2,
+                    (int)(entityBBox.maxp.y + 1) + (int)camera.height / 2,
+                    /*fillColor=*/Style::Color(Style::HOVERED).WithAlpha(25),
+                    /*outlineColor=*/Style::Color(Style::HOVERED));
+            }
+        }
```

This is put right underneath:

```
    // If a marquee selection is in progress, then draw the selection
    // rectangle, as an outline and a transparent fill.
    if(pending.operation == Pending::DRAGGING_MARQUEE) {
        Point2d begin = ProjectPoint(orig.marqueePoint);
        uiCanvas.DrawRect((int)orig.mouse.x + (int)camera.width / 2,
                          (int)begin.x + (int)camera.width / 2,
                          (int)orig.mouse.y + (int)camera.height / 2,
                          (int)begin.y + (int)camera.height / 2,
                          /*fillColor=*/Style::Color(Style::HOVERED).WithAlpha(25),
                          /*outlineColor=*/Style::Color(Style::HOVERED));
```

in draw.cpp

2020-12-17 14:15 UTC, phkahler commented
Those bounding boxes don't make sense to me. They don't seem to bound anything properly? It's also not clear what the bug was that this fixes. You could have opened an issue to report and discuss the bug :-)

2020-12-17 15:00 UTC, vespakoen commented
Those bounding boxes are "debug information", they are not added in this PR, but they were used in the process of fixing the bug.

The actual bug is that the bounding box for normals, which the marquee selection box is compared with, are in the wrong place, see:

<img width="313" alt="Screenshot 2020-12-17 at 15 56 06" src="https://user-images.githubusercontent.com/876117/102503942-88cc1600-4080-11eb-8fe8-cbbefd0b3eda.png">

Those "dots" are the bounding boxes for the normals of the arcs in other places of the drawing.
Those dots were missing the "ProjectPoint3" call:

```diff
-        Vector proj = SK.GetEntity(point[0])->PointGetNum();
+        Vector proj = SS.GW.ProjectPoint3(SK.GetEntity(point[0])->PointGetNum());
 ```

The other problem this PR fixes, is that selecting in 3D didn't work, because the "selection marquee bbox" only works around Z=0, or actually only on the plane perpendicular to the camera, crossing the origin point (if that makes sense).

2020-12-17 15:45 UTC, vespakoen commented
Looks like cubic splines, arcs, images and segments are not working as intented:

<img width="1050" alt="Screenshot 2020-12-17 at 16 45 02" src="https://user-images.githubusercontent.com/876117/102509823-45c17100-4087-11eb-8c5f-02765a51c1c8.png">

2020-12-17 15:59 UTC, phkahler commented
Are all the correct points take into account for the bounding boxes? Remember that curves have control points. The left-most arc in that image looks like the bounding box is taking 2 control points (one for each ~90 degrees) into account but not the one end point that is outside the box.  Based on the text entity it looks like these are determined after an entity is converted to splines which is good. No need to include the center point of an arc or the corners of the text.

2020-12-17 16:04 UTC, vespakoen commented
I found the problem, see: https://github.com/solvespace/solvespace/pull/860/files
The loop that includes all the bezier points into the BBox didn't run all the way to the end.

I also added a bounding box to images.

The last thing I noticed is that the BBox of arcs are a bit bigger than they should be, also, when drawing a segment at 45 degrees, the BBox get's pretty big, maybe we should spend a little more resources here and implement more accurate bboxes & bbox hit testing?

<img width="3200" alt="Screenshot 2020-12-17 at 16 58 55" src="https://user-images.githubusercontent.com/876117/102512121-efa1fd00-4089-11eb-8a82-11247ae0317f.png">

2020-12-17 16:15 UTC, phkahler commented
Good catch.  Diagonal segments will be problematic. These are axis-aligned BBoxes, so that's going to be a given. As for arcs and splines, the convex hull of the control points is guaranteed to contain the curve but that isn't as tight as you can get.  It is conceivable to take the derivatives of the spline polynomials and solve for the T parameter where the x,y, or z derivative is zero. That will give the locations of the extremes in x y z. We'd need to take all 3 derivatives separately because each coordinate has its own equation in T. The good news is we only support 3rd degree so the derivative is never more than 2nd degree. I had considered writing a BBox function in ratpoly that does this but there are a million other things too ;-) You also get into the cost/benefit of more time calculating a bbox vs the time it saves by using it in intersection tests.

BTW does this mean that hovering over the end of that arc would not have highlighted it without the fix?

2020-12-17 16:21 UTC, vespakoen commented
Thanks for the info, so I guess the simple BBox is fine for now =)

And correct,

- Selecting a box around the "dead zones" did not select anything
- Selecting could randomly include normals of arcs somewhere totally else
- Selecting segments using a marquee didn't work (although it oddly selects a segment sometimes when a point is included in the selection?)

2020-12-17 18:31 UTC, ruevs commented
Yeah - selection has always been "funny". But please give me a few days to look at this carefully on a computer.

2020-12-21 13:09 UTC, ruevs requested changes
@vespakoen
- Split in two commits (see the comments in the code).
- Remove the image selection (in my opinion).

2020-12-21 13:09 UTC, ruevs commented on src/drawentity.cpp
> +    *hasBBox = (IsPoint() || IsNormal() || type == Type::IMAGE || !sbl->l.IsEmpty());
Again "no images in selection" is intentional in my opinion.

2020-12-21 13:09 UTC, ruevs commented on src/drawentity.cpp
> +        Vector proj = SS.GW.ProjectPoint3(SK.GetEntity(point[0])->PointGetNum());
OK this is also absolutely a bug an can be included with the `i <= sb.deg;` below.

2020-12-21 13:09 UTC, ruevs commented on src/draw.cpp
> +                                  Vector::From(orig.mouse.x,   orig.mouse.y,   VERY_POSITIVE));
Definitely fixes the marquee selection when the view is rotated. However I have to understand the code much better in order to say what the Z depth of the `marqueeBBox` should be.

Perhaps separate this change as a different commit? e.g.

> Fix marquee selection when the view is rotated away from the working plane.

2020-12-21 15:04 UTC, vespakoen commented
I split this PR up into 3 commits, and removed the IMAGE selection.

2020-12-21 21:00 UTC, ruevs approved these changes
Looks good. Works good. I'll merge this.

2020-12-21 21:00 UTC, merged