remember auto-removed constraints for undo
solvespace/solvespace pull request #929
Opened 2021-02-07 17:01 UTC by robnee

This PR adds calls to `UndoRemember` before auto-removing constraints when adding midpoint or symmetric constraints.  The subsequent call to `AddConstraint` is changed to `rememberForUndo=false` in order to prevent requiring the user to undo twice to return to the starting state.

Fixes #928

2021-02-10 01:46 UTC, phkahler commented
@robnee  Looks good except the midpoint one has an early exit in the else{} clause. Might want to put an undoremember in both the if and elseif.

2021-02-10 01:54 UTC, robnee commented
@phkahler Thanks!  I'll take a look at that.

also, there is a patch in there for the wayland error you noticed when using deprecated gtk popup.  Did you check that too?  I should have done that as a separate PR I suppose but I found these at the same time.  Do you want to close this and I can resubmit 2 separate PRs after I look at the elseif?

2021-02-10 02:03 UTC, phkahler commented
@robnee  No need to resubmit, just fix the one and I'll merge them both.  So yes, I tried the other commit and it seems to work. Getting rid of depricated GTK stuff is good ;-)

2021-02-10 23:12 UTC, ruevs requested changes

2021-02-10 23:12 UTC, ruevs commented on src/constraint.cpp
>                  // normal to the workplane
This needs to be taken into account as well.
Can be reproduced with "Sketch | Anywhere in 3D" then `Y`
Get the error dialog.
Then you need to undo two times, to undo the last operation before the failed symmetric constraint.

2021-02-11 01:01 UTC, robnee commented
@ruevs. Thanks!  It started to get a little clumsy with the edge cases.  I rewrote it slightly to solve the edge cases and make the undo group handling clearer.  Thoughts?

2021-02-14 21:44 UTC, phkahler commented
Any chance you could squash the 3 undo related commits?

2021-02-15 07:38 UTC, ruevs commented
> @ruevs. Thanks! It started to get a little clumsy with the edge cases. I rewrote it slightly to solve the edge cases and make the undo group handling clearer. Thoughts?

@robnee Now it works as it should. But please squash (the non-GTK) commits into one.

2021-02-16 14:38 UTC, robnee commented
I squashed the commits and took out the gtk change which I will resubmit together with a few other deprecation fixes.  Are any other changes needed here?

2021-02-16 16:49 UTC, phkahler commented
I'll merge it. We like commits on the main branch to be clean, vs having the bugs worked out there over several commits. I think you've done the work on this one now ;-)

2021-02-16 16:49 UTC, merged